# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      # Check for updates to Ruby Gems every day
      interval: 'daily'
