title: "GNU Octave - Packages"
description: >-
  Extend GNU Octave's functionality by packages. Find many of them here.
logo: "/assets/octave-logo-512.png"
lang: en

repository: gnu-octave/packages
url: https://gnu-octave.github.io

pkg_icon: "/assets/pkg.png"

markdown_ext: "markdown,md,yaml"

plugins:
  - jekyll-feed

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - LICENSE
  - README.md
  - doc/
  - assets/ci/
