---
layout: "package"
permalink: "database/"
description: >-
  Interface to SQL databases, currently only postgresql using libpq.
icon: "https://octave.sourceforge.io/pkg_icon/database.png"
links:
- icon: "far fa-copyright"
  label: "GPL-3.0-or-later"
  url: "https://sourceforge.net/p/octave/database/ci/default/tree/COPYING"
- icon: "fas fa-rss"
  label: "news"
  url: "https://sourceforge.net/p/octave/database/ci/default/tree/NEWS"
- icon: "fas fa-code-branch"
  label: "repository"
  url: "https://sourceforge.net/p/octave/database/ci/default/tree/"
- icon: "fas fa-th-list"
  label: "function reference"
  url: "https://octave.sourceforge.io/database/overview.html"
- icon: "fas fa-book"
  label: "package documentation"
  url: "https://octave.sourceforge.io/database/package_doc/"
- icon: "fas fa-bug"
  label: "report a problem"
  url: "https://savannah.octave.org/?Action=get&Format=HTMLCSS&Title=[octave%20forge]%20(database)"
maintainers:
- name: "Olaf Till"
  contact: "i7tiol@t-online.de"
versions:
- id: "2.4.4"
  date: "2019-03-13"
  sha256: "3761962f08beed41aadae27f8a14336b1ad5bcdc046861fa325c82d8943916b0"
  url: "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/database-2.4.4.tar.gz"
  depends:
  - "octave (>= 4.0.0)"
  - "struct (>= 1.0.12)"
  - "pkg"
  ubuntu2204:
  - "libpq-dev"
---
